module.exports = [
  {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "Times Food",
    url: "https://recipes.timesofindia.com",
    logo: {
      "@type": "ImageObject",
      url: "https://static.toiimg.com/thumb/65949362.cms?width=600&height=60",
      width: 600,
      height: 60,
    },
  },
  {
    "@context": "http://schema.org/",
    "@type": "Recipe",
    url: "https://recipes.timesofindia.com/recipes/mumbai-style-vada-pav/rs80920657.cms",
    name: "Mumbai-style Vada pav Recipe",
    image: "https://static.toiimg.com/thumb/80920657.cms?width=1200&height=900",
    author: { "@type": "Thing", name: "TNN" },
    datePublished: "2021-02-15T13:42:17+05:30",
    description:
      "Mumbai is famous for its lip-smacking street food. From Bhelpuri and Pav Bhaji to Gola Chuski and Misal Pav, Mumbai has a lot to offer. But do you know what is that common street food that is every Mumbaikar's go-to snack? It is the classic Vada Pav, which you can find with most street vendors. With crispy vada stuffed inside a pav, this dish is enjoyed with a green chilli and some chutney on the side. You can also sip it with coffee or tea and enjoy it as a evening snack. So, make sure you try this recipe to make Vada Pav in the authentic Mumbai style.",
    aggregateRating: {
      "@type": "AggregateRating",
      ratingValue: "3",
      reviewCount: "3",
      worstRating: "1",
      bestRating: "5",
    },
    prepTime: "PT15M",
    totalTime: "PT30M",
    keywords:
      "Mumbai-style Vada pav recipe, Maharashtrian, cook Mumbai-style Vada pav, Road Trip",
    recipeYield: "6",
    recipeCategory: "Appetizers",
    recipeCuisine: "Maharashtrian",
    nutrition: {
      "@type": "NutritionInformation",
      servingSize: "1 bowl",
      calories: "287 cal",
    },
    recipeIngredient: [
      "2 Numbers potato boiled,grated",
      "0 As required refined oil ",
      "1 teaspoon mustard seeds ",
      "1 stalk curry leaves ",
      "1 teaspoon garlic paste ",
      "1 teaspoon ginger paste ",
      "1 Numbers green chilli chopped",
      "1 tablespoon coriander leaves chopped",
      "1 teaspoon turmeric ",
      "1 tablespoon lemon juice ",
      "2 tablespoon gram flour (besan) ",
      "2 tablespoon rice flour ",
      "1/2 teaspoon red chilli powder ",
      "1/4 teaspoon asafoetida ",
      "1/2 cup water ",
      "0 As required salt ",
      "6 Numbers pav ",
      "2 tablespoon butter ",
    ],
    recipeInstructions: ["Haloe", "Haloe", "Haloe", "Haloe", "Haloe"],
  },
  {
    "@context": "http://schema.org/",
    "@type": "creativework",
    headline: "Mumbai-style Vada pav Recipe",
    datemodified: "2021-02-15T13:42:35+05:30",
    text: "",
  },
  [
    {
      "@context": "http://schema.org/",
      "@type": "UserComments",
      commentText: "Nice recipe",
      commentTime: "10 Mar, 2021 04:50 PM",
    },
    {
      "@context": "http://schema.org/",
      "@type": "UserComments",
      commentText: "Wonderful recipe",
      commentTime: "19 Feb, 2021 11:25 AM",
    },
    {
      "@context": "http://schema.org/",
      "@type": "UserComments",
      commentText: "Wonderful recipe",
      commentTime: "19 Feb, 2021 11:25 AM",
    },
  ],
  {
    "@context": "http://schema.org/",
    "@type": "ItemList",
  },
];
